"""
Script: analyze_report.py

Purpose:
    To parse and summarize the CSV report generated by the 'clean_speaker_segments' tool.

Description:
    This script reads a 'report.csv' file, calculates statistics on the cleaning process (accepted vs.
    rejected clips), and aggregates the reasons for rejection (e.g., low similarity score, silence).
    It outputs a concise summary to the console, helping users understand the quality and yield of
    the speaker segment cleaning stage.
"""

import csv
from pathlib import Path
from collections import Counter

def analyze_report(csv_path: str):
    path = Path(csv_path)
    if not path.exists():
        print(f"Error: File not found: {path}")
        return

    stats = Counter()
    reasons = Counter()
    total = 0

    with open(path, mode='r', encoding='utf-8') as f:
        reader = csv.DictReader(f)
        for row in reader:
            total += 1
            decision = row.get('decision', 'unknown')
            reason = row.get('reason', 'n/a')
            
            stats[decision] += 1
            if decision != 'kept':
                reasons[reason] += 1

    print(f"\n--- Cleaning Report Summary ---")
    print(f"File: {path}")
    print(f"Total files processed: {total}")
    print(f"\nDecisions:")
    for decision, count in stats.items():
        percentage = (count / total) * 100 if total > 0 else 0
        print(f"  - {decision}: {count} ({percentage:.1f}%)")

    if reasons:
        print(f"\nRejection/Filter Reasons:")
        for reason, count in reasons.items():
            print(f"  - {reason if reason else 'unspecified'}: {count}")
    print("-" * 32 + "\n")

if __name__ == "__main__":
    report_path = "/mnt/sdc3/Documents/speech-dataset-generator/data/output/Family Guy.S01-S21.1080p.H265/final/cleaned/report.csv"
    analyze_report(report_path)
