"""
Script: finetune.py

Purpose:
    To finetune the Spark-TTS (0.5B) model using a custom audio dataset.

Description:
    This script adapts the logic from examplefinetune.py to train on a local AudioFolder 
    dataset. It uses the unsloth library for optimized training and the Spark-TTS architecture.
"""

import os
import sys
import torch
import numpy as np
from pathlib import Path
from datasets import load_dataset
from unsloth import FastModel
from huggingface_hub import snapshot_download
import torchaudio.transforms as T
from trl import SFTConfig, SFTTrainer

# Ensure project root is in path
sys.path.insert(0, str(Path(__file__).resolve().parent))

# 1. Setup Model and Constants
max_seq_length = 2048
dataset_path = "tts_dataset_output"  # Path to your custom AudioFolder dataset

# Download Spark-TTS model if not already present
if not os.path.exists("Spark-TTS-0.5B"):
    snapshot_download("unsloth/Spark-TTS-0.5B", local_dir="Spark-TTS-0.5B")

# Clone repository for tokenizer code if needed
if not os.path.exists("Spark-TTS"):
    os.system("git clone https://github.com/SparkAudio/Spark-TTS")

sys.path.append('Spark-TTS')
from sparktts.models.audio_tokenizer import BiCodecTokenizer
from sparktts.utils.audio import audio_volume_normalize

# Load Model
model, tokenizer = FastModel.from_pretrained(
    model_name="Spark-TTS-0.5B/LLM",
    max_seq_length=max_seq_length,
    dtype=torch.float32, # Spark requires float32
    full_finetuning=True,
    load_in_4bit=False,
)

# Add LoRA
model = FastModel.get_peft_model(
    model,
    r=128,
    target_modules=["q_proj", "k_proj", "v_proj", "o_proj", "gate_proj", "up_proj", "down_proj"],
    lora_alpha=256,
    lora_dropout=0,
    bias="none",
    use_gradient_checkpointing="unsloth",
    random_state=3407,
)

# 2. Data Preparation
print(f"Loading local dataset from {dataset_path}...")
dataset = load_dataset("audiofolder", data_dir=dataset_path, split="train")

# Initialize Audio Tokenizer
audio_tokenizer = BiCodecTokenizer("Spark-TTS-0.5B", "cuda")

def extract_wav2vec2_features(wavs: torch.Tensor) -> torch.Tensor:
    if wavs.shape[0] != 1:
        raise ValueError(f"Expected batch size 1, but got shape {wavs.shape}")
    wav_np = wavs.squeeze(0).cpu().numpy()

    processed = audio_tokenizer.processor(
        wav_np,
        sampling_rate=16000,
        return_tensors="pt",
        padding=True,
    )
    input_values = processed.input_values.to(audio_tokenizer.feature_extractor.device)
    model_output = audio_tokenizer.feature_extractor(input_values)

    if model_output.hidden_states is None:
        raise ValueError("Wav2Vec2Model did not return hidden states.")

    feats_mix = (
        model_output.hidden_states[11] + model_output.hidden_states[14] + model_output.hidden_states[16]
    ) / 3
    return feats_mix

def formatting_audio_func(example):
    # transcription field comes from metadata.csv generated by package_hf_dataset.py
    text = example["transcription"]
    audio_array = example["audio"]["array"]
    sampling_rate = example["audio"]["sampling_rate"]

    target_sr = audio_tokenizer.config['sample_rate']

    if sampling_rate != target_sr:
        resampler = T.Resample(orig_freq=sampling_rate, new_freq=target_sr)
        audio_tensor_temp = torch.from_numpy(audio_array).float()
        audio_array = resampler(audio_tensor_temp).numpy()

    if audio_tokenizer.config["volume_normalize"]:
        audio_array = audio_volume_normalize(audio_array)

    ref_wav_np = audio_tokenizer.get_ref_clip(audio_array)

    audio_tensor = torch.from_numpy(audio_array).unsqueeze(0).float().to(audio_tokenizer.device)
    ref_wav_tensor = torch.from_numpy(ref_wav_np).unsqueeze(0).float().to(audio_tokenizer.device)

    feat = extract_wav2vec2_features(audio_tensor)

    batch = {
        "wav": audio_tensor,
        "ref_wav": ref_wav_tensor,
        "feat": feat.to(audio_tokenizer.device),
    }

    semantic_token_ids, global_token_ids = audio_tokenizer.model.tokenize(batch)

    global_tokens = "".join(
        [f"<|bicodec_global_{i}|>" for i in global_token_ids.squeeze().cpu().numpy()]
    )
    semantic_tokens = "".join(
        [f"<|bicodec_semantic_{i}|>" for i in semantic_token_ids.squeeze().cpu().numpy()]
    )

    inputs = [
        "<|task_tts|>",
        "<|start_content|>",
        text,
        "<|end_content|>",
        "<|start_global_token|>",
        global_tokens,
        "<|end_global_token|>",
        "<|start_semantic_token|>",
        semantic_tokens,
        "<|end_semantic_token|>",
        "<|im_end|>"
    ]
    inputs = "".join(inputs)
    return {"text": inputs}

print("Tokenizing dataset (this may take a while)...")
dataset = dataset.map(formatting_audio_func, remove_columns=["audio", "transcription", "speaker_id"])

print("Moving Bicodec model and Wav2Vec2Model to CPU to save VRAM.")
audio_tokenizer.model.cpu()
audio_tokenizer.feature_extractor.cpu()
torch.cuda.empty_cache()

# 3. Training
trainer = SFTTrainer(
    model=model,
    tokenizer=tokenizer,
    train_dataset=dataset,
    dataset_text_field="text",
    max_seq_length=max_seq_length,
    packing=False,
    args=SFTConfig(
        per_device_train_batch_size=2,
        gradient_accumulation_steps=4,
        warmup_steps=5,
        max_steps=1200, # Increased for better convergence
        save_steps=100, # Save intermediate checkpoints
        learning_rate=2e-4,
        fp16=False,
        bf16=False,
        logging_steps=1,
        optim="adamw_8bit",
        weight_decay=0.01,
        lr_scheduler_type="linear",
        seed=3407,
        output_dir="outputs_tts",
        report_to="none",
    ),
)

print("Starting training...")
trainer.train()

# 4. Save the model
print("Saving LoRA adapters...")
model.save_pretrained("tts_lora")
tokenizer.save_pretrained("tts_lora")

print("Finetuning complete! LoRA adapters saved to 'tts_lora'.")
